[package]
name = "snake_ai"
version = "0.1.0"
edition = "2021"

[lib]
name = "snake_ai"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.25.1", features = ["extension-module"] }
once_cell = "1"
rand = "0.9.2"

